### ISSUE TITLE
Apa saja yg harus diketahui oleh para PHP Dev?

### ISSUE THREAD

**Issue by awidiyadew** [BaliPHP/yangphpdevelopersharustahu#1]

**Comment by erlangp** [comment]
HTTP Fundamentals
https://symfony.com/doc/current/introduction/http_fundamentals.html

**Comment by satyakresna** [comment]
Halo, tks ya @erlangp . Aku akan simpan sebagai draft news letter.

**Comment by satyakresna** [comment]
Aku close issue ini.
